#### FFHQ  ####
python crop.py --input_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet\(IJCAI\)/vision_figure/R4_Compare_Methods/FFHQ/Diffusion_FAE
python crop.py --input_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet\(IJCAI\)/vision_figure/R4_Compare_Methods/FFHQ/StyleGAN-ADA
python crop.py --input_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet\(IJCAI\)/vision_figure/R4_Compare_Methods/FFHQ/TediGAN

python mask_generation.py --input_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/FFHQ/Diffusion_FAE/crop" --output_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/FFHQ/Diffusion_FAE/mask"
python mask_generation.py --input_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/FFHQ/StyleGAN-ADA/crop" --output_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/FFHQ/StyleGAN-ADA/mask"
python mask_generation.py --input_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/FFHQ/TediGAN/crop" --output_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/FFHQ/TediGAN/mask"

python merge_image.py --input_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/FFHQ/Diffusion_FAE/crop"  --mask_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/FFHQ/Diffusion_FAE/mask" --save_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/FFHQ/Diffusion_FAE/result" 
python merge_image.py --input_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/FFHQ/StyleGAN-ADA/crop"  --mask_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/FFHQ/StyleGAN-ADA/mask" --save_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/FFHQ/StyleGAN-ADA/result" 
python merge_image.py --input_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/FFHQ/TediGAN/crop"  --mask_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/FFHQ/TediGAN/mask" --save_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/FFHQ/TediGAN/result" 

#### CelebA #########
python crop.py --input_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet\(IJCAI\)/ZAQIZABA/search_image_code/CelebA
python mask_generation.py --input_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/ZAQIZABA/search_image_code/CelebA/crop" --output_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/ZAQIZABA/search_image_code/CelebA/mask"
python merge_image.py --input_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/ZAQIZABA/search_image_code/CelebA/crop"  --mask_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/ZAQIZABA/search_image_code/CelebA/mask" --save_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/input/result" 


python crop.py --input_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet\(IJCAI\)/vision_figure/R4_Compare_Methods/CelebA/Diffusion_FAE
python crop.py --input_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet\(IJCAI\)/vision_figure/R4_Compare_Methods/CelebA/Collaborative_Diffusion
python crop.py --input_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet\(IJCAI\)/vision_figure/R4_Compare_Methods/CelebA/Composable_Diffusion
python crop.py --input_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet\(IJCAI\)/vision_figure/R4_Compare_Methods/CelebA/InstantID
python crop.py --input_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet\(IJCAI\)/vision_figure/R4_Compare_Methods/CelebA/Photomaker

python mask_generation.py --input_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/Diffusion_FAE/crop" --output_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/Diffusion_FAE/mask"
python mask_generation.py --input_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/Collaborative_Diffusion/crop" --output_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/Collaborative_Diffusion/mask"
python mask_generation.py --input_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/Composable_Diffusion/crop" --output_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/Composable_Diffusion/mask"
python mask_generation.py --input_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/InstantID/crop" --output_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/InstantID/mask"
python mask_generation.py --input_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/Photomaker/crop" --output_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/Photomaker/mask"

python merge_image.py --input_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/Diffusion_FAE/crop"  --mask_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/Diffusion_FAE/mask" --save_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/Diffusion_FAE/result" 
python merge_image.py --input_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/Collaborative_Diffusion/crop"  --mask_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/Collaborative_Diffusion/mask" --save_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/Collaborative_Diffusion/result" 
python merge_image.py --input_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/Composable_Diffusion/crop"  --mask_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/Composable_Diffusion/mask" --save_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/Composable_Diffusion/result" 
python merge_image.py --input_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/InstantID/crop"  --mask_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/InstantID/mask" --save_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/InstantID/result" 
python merge_image.py --input_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/Photomaker/crop"  --mask_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/Photomaker/mask" --save_folder "/workspace/AdBRC/xieyuan/Beautytask/3DFACENet(IJCAI)/vision_figure/R4_Compare_Methods/CelebA/Photomaker/result" 