python test_now.py --input_folder IMG_0092  --output_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet/bfm_transform/coef2mesh_demo/NoW_TEST_CM/IMG_0092
python test_now.py --input_folder IMG_0151  --output_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet/bfm_transform/coef2mesh_demo/NoW_TEST_CM/IMG_0151
python test_now.py --input_folder IMG_0214  --output_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet/bfm_transform/coef2mesh_demo/NoW_TEST_CM/IMG_0214
python test_now.py --input_folder IMG_0254  --output_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet/bfm_transform/coef2mesh_demo/NoW_TEST_CM/IMG_0254
python test_now.py --input_folder IMG_0284  --output_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet/bfm_transform/coef2mesh_demo/NoW_TEST_CM/IMG_0284
python test_now.py --input_folder IMG_0365  --output_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet/bfm_transform/coef2mesh_demo/NoW_TEST_CM/IMG_0365
python test_now.py --input_folder IMG_0437  --output_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet/bfm_transform/coef2mesh_demo/NoW_TEST_CM/IMG_0437
python test_now.py --input_folder IMG_0468  --output_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet/bfm_transform/coef2mesh_demo/NoW_TEST_CM/IMG_0468
python test_now.py --input_folder IMG_0511  --output_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet/bfm_transform/coef2mesh_demo/NoW_TEST_CM/IMG_0511
python test_now.py --input_folder IMG_0583  --output_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet/bfm_transform/coef2mesh_demo/NoW_TEST_CM/IMG_0583
python test_now.py --input_folder IMG_0621  --output_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet/bfm_transform/coef2mesh_demo/NoW_TEST_CM/IMG_0621
python test_now.py --input_folder IMG_0668  --output_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet/bfm_transform/coef2mesh_demo/NoW_TEST_CM/IMG_0668
python test_now.py --input_folder IMG_0711  --output_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet/bfm_transform/coef2mesh_demo/NoW_TEST_CM/IMG_0711
python test_now.py --input_folder IMG_0757  --output_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet/bfm_transform/coef2mesh_demo/NoW_TEST_CM/IMG_0757
python test_now.py --input_folder IMG_0874  --output_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet/bfm_transform/coef2mesh_demo/NoW_TEST_CM/IMG_0874
python test_now.py --input_folder IMG_0997  --output_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet/bfm_transform/coef2mesh_demo/NoW_TEST_CM/IMG_0997
python test_now.py --input_folder IMG_1031  --output_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet/bfm_transform/coef2mesh_demo/NoW_TEST_CM/IMG_1031
python test_now.py --input_folder IMG_1123  --output_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet/bfm_transform/coef2mesh_demo/NoW_TEST_CM/IMG_1123
python test_now.py --input_folder IMG_1199  --output_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet/bfm_transform/coef2mesh_demo/NoW_TEST_CM/IMG_1199
python test_now.py --input_folder IMG_1299  --output_folder /workspace/AdBRC/xieyuan/Beautytask/3DFACENet/bfm_transform/coef2mesh_demo/NoW_TEST_CM/IMG_1299